/run/initialize

# OpenGL viewer
/vis/open OGL 600x600-0+0

# Set style
/vis/viewer/set/background white
/vis/viewer/set/viewpointThetaPhi 30 60
/vis/viewer/zoom 2.0

# Draw geometry
/vis/drawVolume

# Set visualization attributes
/vis/geometry/set/visibility World 0 false

# Add trajectories
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 10

# Run 1 event
/tracking/verbose 0
/run/beamOn 1
